Controllers/TareaController.cs
using kanban.Models;
using kanban.ViewModels;
using kanban.Repository;
using kanban.Controllers.Helpers;
using Microsoft.AspNetCore.Mvc;

namespace kanban.Controllers
{
    [ApiController]
    [Route("tareas")]
    public class TareaController : Controller
    {
        private readonly ITareaRepository _tareaRepository;
        private readonly ITableroRepository _tableroRepository;
        private readonly IUsuarioRepository _usuarioRepository;
        private readonly ILogger<TareaController> _logger;

        public TareaController(ILogger<TareaController> logger, ITableroRepository tableroRepository, ITareaRepository tareaRepository,IUsuarioRepository usuarioRepository)
        {
            _logger = logger;
            _tableroRepository = tableroRepository;
            _tareaRepository = tareaRepository;
            _usuarioRepository = usuarioRepository;
        }

        [HttpPost("crear/{boardId}")]
        public IActionResult Crear(int boardId, [FromForm] CrearTareaViewModel tareaViewModel)
        {
            try
            {
                if (!LoginHelper.IsLogged(HttpContext)) return RedirectToAction("Index", "Login");

                if (!ModelState.IsValid) return View(tareaViewModel);

                var task = new Tarea
                {
                    IdTablero = tareaViewModel.IdTablero,
                    Nombre = tareaViewModel.Nombre,
                    Descripcion = tareaViewModel.Descripcion,
                    Estado = tareaViewModel.Estado,
                    Color = tareaViewModel.Color,
                    IdUsuarioAsignado = tareaViewModel.IdUsuarioAsignado
                };
                _tareaRepository.Create(boardId, task);
                return RedirectToAction("ListByBoard", new { id = boardId });
            }
            catch (Exception ex)
            {
                _logger.LogError($"Error en el endpoint Crear de TareaController: {ex.Message}");
                return RedirectToAction("Error", "Home");
            }
        }

        [HttpGet("crear/{tableroId}")]
        public IActionResult Crear(int tableroId)
        {
            try
            {
                if (!LoginHelper.IsLogged(HttpContext)) return RedirectToAction("Index", "Login");

                var crearTareaModel = new CrearTareaViewModel
                {
                    IdTablero = tableroId
                };

                var sesionId = int.Parse(LoginHelper.GetUserId(HttpContext));

                if(!LoginHelper.IsAdmin(HttpContext)) {
                    var tableros = _tableroRepository.ListUserBoards(sesionId);
                    var tableroBuscado = tableros.Find(tablero => tablero.Id == tableroId);
                    if (tableroBuscado == null)  return NotFound($"No existe el recurso");
                }

                var usuarios = _usuarioRepository.List();
                List<UsuarioDropBoxViewModel> usuariosViewModel = new();

                foreach (var usuario in usuarios)
                {
                    UsuarioDropBoxViewModel modelo = new(usuario.Id,usuario.NombreDeUsuario);
                    usuariosViewModel.Add(modelo);
                }
                crearTareaModel.Usuarios = usuariosViewModel;

                return View(crearTareaModel);
            }
            catch (Exception ex)
            {
                _logger.LogError($"Error en el endpoint Crear (HttpGet) de TareaController: {ex.Message}");
                return RedirectToAction("Error", "Home");
            }
        }

        [HttpGet("editar/{id}")]
        public IActionResult Editar(int id)
        {
            try
            {                
                if (!LoginHelper.IsLogged(HttpContext)) return RedirectToAction("Index", "Login");

                var tarea = _tareaRepository.GetById(id);
                if (tarea.Id == 0) return NotFound($"No se encontro el recurso.");
                var sesionId = int.Parse(LoginHelper.GetUserId(HttpContext));
                var isAdmin = LoginHelper.IsAdmin(HttpContext);
                

                var tableroTarea = _tableroRepository.GetById(tarea.IdTablero);

                var isOwner = tableroTarea.IdUsuarioPropietario == sesionId;

                
                var usuarios = _usuarioRepository.List();
                List<UsuarioDropBoxViewModel> usuariosViewModel = new();

                foreach (var usuario in usuarios)
                {
                    UsuarioDropBoxViewModel modelo = new(usuario.Id,usuario.NombreDeUsuario);
                    usuariosViewModel.Add(modelo);
                }

                if(!isAdmin && !isOwner && tableroTarea.Id != 0) {    
                    var editarTareaModel = new EditarTareaViewModel
                        {
                            Estado = tarea.Estado,
                        };
                    return View("Operador/Editar",editarTareaModel);
                }

                if(!isAdmin && isOwner) {

                    var editarTareaModel = new EditarTareaViewModel
                        {
                            Id = tarea.Id,
                            Estado = tarea.Estado,
                            Nombre = tarea.Nombre,
                            Descripcion = tarea.Descripcion,
                            Color = tarea.Color,
                            IdUsuarioAsignado = tarea.IdUsuarioAsignado,
                            Usuarios = usuariosViewModel
                        };
                    return View("Operador/EditarAdminTablero",editarTareaModel);
                }

                if(isAdmin) {
                    var tableros = _tableroRepository.List();

                    List<TableroDropBoxViewModel> tableroViewModel = new();

                    foreach (var tablero in tableros)
                    {
                        TableroDropBoxViewModel modelo = new(tablero.Id,tablero.Nombre);
                        tableroViewModel.Add(modelo);
                    }

                    var editarTareaModel = new EditarTareaViewModel
                        {
                            Id = tarea.Id,
                            IdTablero = tarea.IdTablero,
                            Estado = tarea.Estado,
                            Nombre = tarea.Nombre,
                            Descripcion = tarea.Descripcion,
                            Color = tarea.Color,
                            IdUsuarioAsignado = tarea.IdUsuarioAsignado,
                            Usuarios = usuariosViewModel,
                            Tableros = tableroViewModel
                        };
                    return View("Administrador/Editar",editarTareaModel);
                }

                return NotFound($"No existe el recurso.");
            }
            catch (Exception ex)
            {
                _logger.LogError($"Error en el endpoint Editar (HttpGet) de TareaController: {ex.Message}");
                return RedirectToAction("Error", "Home");
            }
        }

        [HttpPost("editar/{id}")]
        public IActionResult Editar(int id, [FromForm] EditarTareaViewModel tareaViewModel)
        {
            try
            {
                if (!LoginHelper.IsLogged(HttpContext)) return RedirectToAction("Index", "Login");

                if (!ModelState.IsValid) return View(tareaViewModel);

                var tarea = _tareaRepository.GetById(id);
                if (tarea.Id == 0) return NotFound($"No se encontro el recurso.");

                var sesionId = int.Parse(LoginHelper.GetUserId(HttpContext));
      
                var isAdmin = LoginHelper.IsAdmin(HttpContext);

                var tableroTarea = _tableroRepository.GetById(tarea.IdTablero);

                var isOwner = tableroTarea.IdUsuarioPropietario == sesionId;
                
                if(!isAdmin && !isOwner && tableroTarea.Id != 0) {    
                    var editarTareaModel = new Tarea
                        {
                            Estado = tareaViewModel.Estado,
                            Id = tarea.Id,
                            IdTablero = tarea.IdTablero,
                            Nombre = tarea.Nombre,
                            Descripcion = tarea.Descripcion,
                            Color = tarea.Color,
                            IdUsuarioAsignado = tarea.IdUsuarioAsignado,
                        };
                        
                    _tareaRepository.Update(id, editarTareaModel);
                }
                if(!isAdmin && isOwner) { 
                    var tareaModel = new Tarea
                    {
                        Id = tareaViewModel.Id,
                        IdTablero = tarea.IdTablero,
                        Estado = tareaViewModel.Estado,
                        Nombre = tareaViewModel.Nombre,
                        Descripcion = tareaViewModel.Descripcion,
                        Color = tareaViewModel.Color,
                        IdUsuarioAsignado = tareaViewModel.IdUsuarioAsignado,
                    };

                    _tareaRepository.Update(id, tareaModel);
                }
                
                if(isAdmin) { 
                    var tareaModel = new Tarea
                    {
                        Id = tareaViewModel.Id,
                        IdTablero = tareaViewModel.IdTablero,
                        Estado = tareaViewModel.Estado,
                        Nombre = tareaViewModel.Nombre,
                        Descripcion = tareaViewModel.Descripcion,
                        Color = tareaViewModel.Color,
                        IdUsuarioAsignado = tareaViewModel.IdUsuarioAsignado,
                    };

                    _tareaRepository.Update(id, tareaModel);
                }
                
                return RedirectToAction("ListByBoard", new { id = tarea.IdTablero });
            }
            catch (Exception ex)
            {

Views/Shared/_Layout.cshtml
@using kanban.Controllers.Helpers
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - kanban</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/tp10.styles.css" asp-append-version="true" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">kanban</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                    <ul class="navbar-nav">
    @if (LoginHelper.IsLogged(this.ViewContext.HttpContext))
    {
        <li class="nav-item">
            <a class="nav-link" asp-area="" asp-controller="Tablero" asp-action="Index">Tableros</a>
        </li> 
        <li class="nav-item">
            <a class="nav-link" asp-area="" asp-controller="Tarea" asp-action="Index">Mis Tareas</a>
        </li>

        @if (LoginHelper.IsAdmin(this.ViewContext.HttpContext))
        {
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Usuario" asp-action="ListarUsuarios">Usuarios</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Tarea" asp-action="ListarTodasLasTareas">Todas Las Tareas</a>
            </li>
        }

        <li class="nav-item">
            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" asp-area="" asp-controller="Usuario" asp-action="Index">Perfil</a>
        </li>
        <li class="nav-item">
            <form class="form-inline my-2 my-lg-0" id="logoutForm"
                  asp-controller="Login" asp-action="Logout" method="post">
                <button class="btn btn-outline-danger my-2 my-sm-0" type="submit">Cerrar sesión</button>
            </form>
        </li>
    }
</ul>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - tp10 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>