Models/Tablero.cs
namespace kanban.Models;
public enum EstadoTarea
{
    Ideas,
    ToDo,
    Doing,
    Review,
    Done
}
public class Tablero
{
    public int Id { get; set; }
    public int IdUsuarioPropietario { get; set; }
    public string Nombre { get; set; }
    public string Descripcion { get; set; }
}

ViewModels/Tablero/CrearTableroViewModel.cs
using System.ComponentModel.DataAnnotations;
namespace kanban.ViewModels;
public class CrearTableroViewModel
{
    [Required(ErrorMessage = "Campo requerido")]
    public int IdUsuarioPropietario { get; set; }
    
    [Required(ErrorMessage = "Campo requerido")]
    public string Nombre { get; set; }
    
    [Required(ErrorMessage = "Campo requerido")]
    public string Descripcion { get; set; }
    public List<UsuarioDropBoxViewModel>? Usuarios { get; set; }
}

ViewModels/Tablero/ListarTablerosConTareasViewModel.cs
namespace kanban.ViewModels;

public class ListarTablerosConTareasViewModel
{
    public string NombreTablero { get; set; }
    public bool EsPropietario { get; set; }
    public List<ListarTareasViewModel> Tareas { get; set; }
}

ViewModels/Tablero/ListarTablerosViewModel.cs
using kanban.Repository;
namespace kanban.ViewModels;
public class ListarTablerosViewModel
{
    public string Nombre { get; set; }
    public string Descripcion { get; set; }
    public string UsuarioPropietario { get; set; }
    public int Id { get; set; }
    private readonly IUsuarioRepository _usuarioRepository;

    public ListarTablerosViewModel(string nombre, string descipcion, int id, int idUsuarioPropietario, IUsuarioRepository usuarioRepository)
    {
        _usuarioRepository = usuarioRepository;
        var user = _usuarioRepository.GetById(idUsuarioPropietario);
        if (user.Id == 0) UsuarioPropietario = "";
        else UsuarioPropietario = user.NombreDeUsuario;
        Nombre = nombre;
        Descripcion = descipcion;
        Id = id;
    }
}

ViewModels/Tablero/ModificarTableroViewModel.cs
using System.ComponentModel.DataAnnotations;
namespace kanban.ViewModels;
public class ModificarTableroViewModel
{
    [Required(ErrorMessage = "Complete el campo")]
    public int IdUsuarioPropietario { get; set; }
    [Required(ErrorMessage = "Complete el campo")]
    public string Nombre { get; set; }
    [Required(ErrorMessage = "Complete el campo")]
    public string Descripcion { get; set; }
    [Required(ErrorMessage = "Complete el campo")]
    public int Id { get; set; }
    public List<UsuarioDropBoxViewModel>? Usuarios { get; set; }
}

ViewModels/Tablero/TableroDropBoxViewModel.cs
namespace kanban.ViewModels;
public class TableroDropBoxViewModel
    {

        public int Id { get; set; }
        public string Nombre { get; set; }
        
        public TableroDropBoxViewModel(int id, string nombre)
        {
            Id = id;
            Nombre = nombre;
        }
    }

Controllers/TableroController.cs
using kanban.Models;
using kanban.Repository;
using kanban.Controllers.Helpers;
using kanban.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace kanban.Controllers
{
    [ApiController]
    [Route("tableros")]
    public class TableroController : Controller
    {
        private readonly ITableroRepository _tableroRepository;
        private readonly ITareaRepository _tareaRepository;
        private readonly IUsuarioRepository _usuarioRepository;
        private readonly ILogger<TableroController> _logger;

        public TableroController(ILogger<TableroController> logger, ITableroRepository tableroRepository, ITareaRepository tareaRepository, IUsuarioRepository usuarioRepository)
        {
            _logger = logger;
            _tableroRepository = tableroRepository;
            _tareaRepository = tareaRepository;
            _usuarioRepository = usuarioRepository;
        }

        [HttpGet("crear")]
        public IActionResult Crear()
        {
            try
            {
                if (!LoginHelper.IsLogged(HttpContext)) return RedirectToAction("Index", "Login");
                
                var crearTableroModel = new CrearTableroViewModel();

                if(LoginHelper.IsAdmin(HttpContext)) {
                    var usuarios = _usuarioRepository.List();
                    List<UsuarioDropBoxViewModel> usuariosViewModel = new();

                    foreach (var usuario in usuarios)
                    {
                        UsuarioDropBoxViewModel modelo = new(usuario.Id,usuario.NombreDeUsuario);
                        usuariosViewModel.Add(modelo);
                    }
                    crearTableroModel.Usuarios = usuariosViewModel;
                    crearTableroModel.IdUsuarioPropietario = int.Parse(LoginHelper.GetUserId(HttpContext));
                    return View("Administrador/Crear",crearTableroModel);
                } else {
                    return View("Operador/Crear",crearTableroModel);
                }

            }
            catch (Exception ex)
            {
                _logger.LogError($"Error en el endpoint Crear de TableroController: {ex.Message}");
                return RedirectToAction("Error", "Home");
            }
        }

        [HttpPost("crear")]
        public IActionResult Crear([FromForm] CrearTableroViewModel crearTableroModel)
        {
            try
            {
                if (!LoginHelper.IsLogged(HttpContext)) return RedirectToAction("Index", "Login");

                if (!ModelState.IsValid) return RedirectToAction("Index", "Home");
                var sesionId = int.Parse(LoginHelper.GetUserId(HttpContext));
                var tablero = new Tablero()
                {
                    Nombre = crearTableroModel.Nombre,
                    Descripcion = crearTableroModel.Descripcion,
                    IdUsuarioPropietario = sesionId
                };

                if (LoginHelper.IsAdmin(HttpContext)) tablero.IdUsuarioPropietario = crearTableroModel.IdUsuarioPropietario;

                _tableroRepository.Create(tablero);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                _logger.LogError($"Error en el endpoint Crear (HttpPost) de TableroController: {ex.Message}");
                return RedirectToAction("Error", "Home");
            }
        }

        [HttpGet]
        public IActionResult Index()
        {
            try
            {
                if (!LoginHelper.IsLogged(HttpContext)) return RedirectToAction("Index", "Login");

                List<Tablero> boards = new();

                ViewBag.EsAdmin = LoginHelper.IsAdmin(HttpContext);

                if (ViewBag.EsAdmin) boards = _tableroRepository.List();

                else boards = _tableroRepository.ListUserBoards(int.Parse(LoginHelper.GetUserId(HttpContext)));

                List<ListarTablerosViewModel> ListarTablerosModel = new();

                foreach (var board in boards)   
                {
                    ListarTablerosViewModel modelo = new(board.Nombre, board.Descripcion, board.Id, board.IdUsuarioPropietario, _usuarioRepository);
                    ListarTablerosModel.Add(modelo);
                }

                return View(ListarTablerosModel);
            }
            catch (Exception ex)
            {
                _logger.LogError($"Error en el endpoint Index de TableroController: {ex.Message}");
                return RedirectToAction("Error", "Home");
            }
        }

        [HttpPost("eliminar/{id}")]
        public IActionResult Eliminar(int id)
        {
            try
            {
                if (!LoginHelper.IsLogged(HttpContext)) return RedirectToAction("Index", "Login");

                var board = _tableroRepository.GetById(id);

                if (board.Id == 0) return NotFound($"No existe el recurso.");

                var sesionId = int.Parse(LoginHelper.GetUserId(HttpContext));

                var isOwner = board.IdUsuarioPropietario == sesionId;

                var isAdmin = LoginHelper.IsAdmin(HttpContext);

                if (isAdmin || isOwner)
                {
                    var tasks = _tareaRepository.ListByBoard(id);

                    foreach (var task in tasks)
                    {
                        _tareaRepository.Delete(task.Id);
                    }
                    
                    _tableroRepository.Delete(id);
                }

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                _logger.LogError($"Error en el endpoint Eliminar de TableroController: {ex.Message}");
                return RedirectToAction("Error", "Home");
            }
        }

        [HttpGet("editar/{id}")]
        public IActionResult Editar(int id)
        {
            try
            {
                if (!LoginHelper.IsLogged(HttpContext)) return RedirectToAction("Index", "Login");

                var board = _tableroRepository.GetById(id);

                if (board.Id == 0) return NotFound($"No existe el recurso.");

                var modificarTableroModel = new ModificarTableroViewModel
                {
                    Nombre = board.Nombre,
                    Descripcion = board.Descripcion,
                    Id = board.Id
                };

                if(LoginHelper.IsAdmin(HttpContext)) {
                var usuarios = _usuarioRepository.List();
                List<UsuarioDropBoxViewModel> usuariosViewModel = new();

                foreach (var usuario in usuarios)
                {
                    UsuarioDropBoxViewModel modelo = new(usuario.Id,usuario.NombreDeUsuario);
                    usuariosViewModel.Add(modelo);
                }
                modificarTableroModel.Usuarios = usuariosViewModel;
                }

                if (!LoginHelper.IsAdmin(HttpContext))
                {
                    var userBoards = _tableroRepository.ListUserBoards(int.Parse(LoginHelper.GetUserId(HttpContext)));
                    var foundBoard = userBoards.Find(board => board.Id == id);
                    if (foundBoard != null) return View("Operador/Editar",modificarTableroModel);
                    else return NotFound($"No existe el tablero con ID {id}");
                }
                else
                {
                    modificarTableroModel.IdUsuarioPropietario = board.IdUsuarioPropietario;
                    return View("Administrador/Editar",modificarTableroModel);
                }
            }
            catch (Exception ex)
            {
                _logger.LogError($"Error en el endpoint Editar (HttpGet) de TableroController: {ex.Message}");
                return RedirectToAction("Error", "Home");
            }
        }

        [HttpPost("editar/{id}")]
        public IActionResult Editar(int id, [FromForm] ModificarTableroViewModel newBoardViewModel)
        {
            try
            {
                if (!LoginHelper.IsLogged(HttpContext)) return RedirectToAction("Index", "Login");

                if (!ModelState.IsValid) return RedirectToAction("Index", "Home");
                var board = _tableroRepository.GetById(id);

                if (board.Id == 0) return NotFound($"No existe el recurso.");
                var sesionId = int.Parse(LoginHelper.GetUserId(HttpContext));
                var newBoard = new Tablero
                {
                    Nombre = newBoardViewModel.Nombre,
                    Descripcion = newBoardViewModel.Descripcion,
                    Id = newBoardViewModel.Id,
                    IdUsuarioPropietario = newBoardViewModel.IdUsuarioPropietario == 0
                    ? board.IdUsuarioPropietario
                    : newBoardViewModel.IdUsuarioPropietario
                };

                if (!LoginHelper.IsAdmin(HttpContext))
                {
                    var userBoards = _tableroRepository.ListUserBoards(sesionId);
                    var foundBoard = userBoards.Find(board => board.Id == id);
                    if (foundBoard != null)
                    {
                        newBoard.IdUsuarioPropietario = sesionId;
                        _tableroRepository.Update(id, newBoard);
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        return NotFound($"Recurso no encontrado.");
                    }
                }
                _tableroRepository.Update(id, newBoard);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                _logger.LogError($"Error en el endpoint Editar (HttpPost) de TableroController: {ex.Message}");
                return RedirectToAction("Error", "Home");
            }
        }
    }
}

Views/Tablero/Crear.cshtml
@using kanban.ViewModels
@model CrearTableroViewModel

<form asp-controller="Tablero" asp-action="Crear" method="post">
    <div class="mb-3">
        <label for="lbl.nombre" class="form-label" asp-for="Nombre">Nombre: </label>
        <input type="text" class="form-control" id="lbl.nombre" asp-for="Nombre">
    </div>

    <div class="mb-3">
        <label for="lbl.descripcion" class="form-label" asp-for="Descripcion">Descripción: </label>
        <input type="text" class="form-control" id="lbl.descripcion" asp-for="Descripcion">
    </div>


   @if (Model.IsAdmin)
    {
        <div class="mb-3">
            <label for="lbl.IdUsuarioPropietario" class="form-label" asp-for="IdUsuarioPropietario">Usuario Propietario:</label>
            @Html.DropDownListFor(model => model.IdUsuarioPropietario, 
                      new SelectList(Model.Usuarios, "Id", "Nombre", Model.IdUsuarioPropietario), 
                      "-- Seleccionar usuario propietario --", 
                      new { @class = "form-select" })
        </div>
    }

    <button type="submit" class="btn btn-primary">Crear</button>
</form>

Views/Tablero/Editar.cshtml
@model kanban.ViewModels.ModificarTableroViewModel

@{
    ViewData["Title"] = "Editar Tablero";
}

<h2>Editar Tablero</h2>

<form asp-controller="Tablero" asp-action="Editar" method="post">
    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <label asp-for="Nombre">Nombre:</label>
        <input asp-for="Nombre" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Descripcion">Descripcion:</label>
        <input asp-for="Descripcion" class="form-control" />
    </div>
    @if (ViewBag.EsAdmin)
    {
         <div class="mb-3">
            <label for="lbl.IdUsuarioPropietario" class="form-label" asp-for="IdUsuarioPropietario">Usuario Propietario:</label>
            @Html.DropDownListFor(model => model.IdUsuarioPropietario, 
                      new SelectList(Model.Usuarios, "Id", "Nombre", Model.IdUsuarioPropietario), 
                      "-- Seleccionar usuario propietario --", 
                      new { @class = "form-select" })
        </div>
    }
    <button type="submit" class="btn btn-primary">Guardar Cambios</button>
</form>

Views/Tablero/Index.cshtml
@{
    ViewData["Title"] = "Tableros";
}

@using kanban.ViewModels
@model List<ListarTablerosViewModel>

<h2>Mis Tableros</h2>
<a asp-controller="Tablero" asp-action="Crear">Crear Tablero</a>

<table class="table table-dark">
    <thead>
        <tr>
            <th hidden>ID</th>

            @if (ViewBag.EsAdmin)
            {
                <th>Usuario Propietario</th>
            }
            <th>Nombre</th>
            <th>Descripcion</th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var tablero in Model)
        {
            <tr>
                <td hidden>@tablero.Id</td>
                @if (ViewBag.EsAdmin)
                {
                    <td>@tablero.UsuarioPropietario</td>
                }
                <td>@tablero.Nombre</td>
                <td>@tablero.Descripcion</td>
                <td>
                    <a asp-controller="Tablero" asp-action="Editar" asp-route-id="@tablero.Id">Editar</a>
                </td>
                <td>
                    <a asp-controller="Tarea" asp-action="ListByBoard" asp-route-id="@tablero.Id">Ver Tareas</a>
                </td>
                <td>
                    <a asp-controller="Tarea" asp-action="Crear" asp-route-tableroId="@tablero.Id">Crear Tarea</a>
                </td>
                <td>
                    <form asp-controller="Tablero" asp-action="Eliminar" asp-route-id="@tablero.Id" method="post"
                        onsubmit="return confirm('¿Estás seguro de que deseas eliminar este tablero?')">
                        <input type="hidden" name="_method" value="delete" />
                        <button type="submit">Eliminar</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>